### ISSUE TITLE
FileNotFoundException: /scm-source.json on composer start

### ISSUE THREAD

**Issue by SergKam** [adyach/nakadi-docker#2]
Everything is working but this just polluting the logs.

```
nakadi_1     | [2018-07-13 09:43:35.547Z] [WARN] [null] [main] [org.zalando.nakadi.controller.EventStreamController] --- Failed to read scm-source.json file from /scm-source.json
nakadi_1     | java.io.FileNotFoundException: /scm-source.json (No such file or directory)
nakadi_1     | 	at java.io.FileInputStream.open0(Native Method)
nakadi_1     | 	at java.io.FileInputStream.open(FileInputStream.java:195)
nakadi_1     | 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
nakadi_1     | 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
nakadi_1     | 	at org.zalando.nakadi.controller.VersionController.loadScmSource(VersionController.java:91)
nakadi_1     | 	at org.zalando.nakadi.controller.VersionController.<init>(VersionController.java:82)
nakadi_1     | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
nakadi_1     | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
nakadi_1     | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
nakadi_1     | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
nakadi_1     | 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
nakadi_1     | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
nakadi_1     | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
nakadi_1     | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
nakadi_1     | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
nakadi_1     | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
nakadi_1     | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
nakadi_1     | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
nakadi_1     | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
nakadi_1     | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
nakadi_1     | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
nakadi_1     | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
nakadi_1     | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
nakadi_1     | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
nakadi_1     | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
nakadi_1     | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
nakadi_1     | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
nakadi_1     | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
nakadi_1     | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
nakadi_1     | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
nakadi_1     | 	at org.zalando.nakadi.Application.main(Application.java:12)
nakadi_1     | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nakadi_1     | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nakadi_1     | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nakadi_1     | 	at java.lang.reflect.Method.invoke(Method.java:498)
nakadi_1     | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
nakadi_1     | 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by adyach** [comment]
it is not really the issue of nakadi-docker, it is related to how Nakadi gets its version. I filled a ticket to improve it https://github.com/zalando/nakadi/issues/912
